### ISSUE TITLE
Cookie expiration date

### ISSUE THREAD

**Issue by codeheroics** [buildo/react-cookie-banner#23]
Hi,

The current cookie expiration date is set to 1 year after the acceptance of the cookie. Does the law require yearly approval, or is it just a default for the code? (and if so, couldn't the cookie be set with a much expiration date way later in time, so as to not bother users again a year after acceptance?)

**Comment by FrancescoCioria** [comment]
Hi @codeheroics 
Yes, currently the expiration date is [hardcoded to 1 year](https://github.com/buildo/react-cookie-banner/blob/master/src/CookieBanner.js#L93)

I think this is very opinionated but setting it to 10 years would be opinionated too :)

If you agree I can make it customizable through props and leave 1 year as default to avoid breaking changes. Would this be ok for you?

**Comment by codeheroics** [comment]
Yes, it would be great :)

**Comment by FrancescoCioria** [comment]
@codeheroics I just released `v0.0.16` with the new prop `cookieExpiration`

`cookieExpiration` can be either an integer representing the **seconds** since its expiration or an object structured like this if you don't want to do the math :)
```js
{
  years: ?Number,
  days : ?Number,
  hours: ?Number
}
```

the default remains one year (`{ years: 1 }`) to avoid adding a breaking change

**Comment by codeheroics** [comment]
Awesome, thanks! :)

**Comment by gabro** [comment]
@FrancescoCioria I just noticed the README wasn't updated. Can you take care of it?
